routes/web.php
<?php

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    // Ignores notices and reports all other kinds... and warnings
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
    // error_reporting(E_ALL ^ E_WARNING); // Maybe this is enough
}

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => '/'], function () {
	Route::get('/', ['as' => 'homePage', 'uses' => 'WebController@index']);
	Route::get('/filter-caleg', ['as' => 'filterCaleg', 'uses' => 'WebController@get']);
	Route::get('/mobile', ['as' => 'mobilePage', 'uses' => 'WebController@mobile']);
	Route::get('/get-all-vote', ['as' => 'allVoteRoute', 'uses' => 'VoteController@show']);
	Route::get('/get-all-parpol', ['as' => 'allParpolRoute', 'uses' => 'ParpolController@show']);
	Route::get('/get-all-kabupaten', ['as' => 'allKabupatenRoute', 'uses' => 'KabupatenController@show']);
	Route::get('/get-all-kecamatan', ['as' => 'allKecamatanRoute', 'uses' => 'KecamatanController@show']);
	Route::get('/get-all-desa', ['as' => 'allDesaRoute', 'uses' => 'DesaController@show']);
	Route::get('/get-all-dapil', ['as' => 'allDapilRoute', 'uses' => 'DapilController@show']);
	Route::get('/get-all-wilayahdapil/{id}', ['as' => 'allWilayahdapilRoute', 'uses' => 'DapilController@area']);
	Route::get('/get-all-wilayahdetail/{id}', ['as' => 'wilayahDetailRoute', 'uses' => 'DapilController@area_detail']);
	Route::get('/get-all-tps', ['as' => 'allTpsRoute', 'uses' => 'TpsController@show']);
	Route::get('/get-all-usergroup', ['as' => 'allUsergroupRoute', 'uses' => 'UsergroupController@show']);
	Route::get('/get-all-caleggroup', ['as' => 'allCaleggroupRoute', 'uses' => 'CaleggroupController@show']);
	Route::get('/get-all-caleg', ['as' => 'allCalegRoute', 'uses' => 'CalegController@show']);
	
});

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin'], 'as' => 'admin.'], function () {
	Route::get('/dashboard', ['as' => 'dashboardRoute', 'uses' => 'DashboardController@index']);


	/*** For Master ***/
	/*** For Kabupaten ***/
	Route::resource('kabupaten', 'KabupatenController');
	Route::get('/get-kabupaten', ['as' => 'getKabupatenRoute', 'uses' => 'KabupatenController@get']);
	Route::get('/kabupaten/published/{id}', ['as' => 'publishedKabupatenRoute', 'uses' => 'KabupatenController@published']);
	Route::get('/kabupaten/unpublished/{id}', ['as' => 'unpublishedKabupatenRoute', 'uses' => 'KabupatenController@unpublished']);
	/*** For Kecamatan ***/
	Route::resource('kecamatan', 'KecamatanController');
	Route::get('/get-kecamatan', ['as' => 'getKecamatanRoute', 'uses' => 'KecamatanController@get']);
	Route::get('/kecamatan/published/{id}', ['as' => 'publishedKecamatanRoute', 'uses' => 'KecamatanController@published']);
	Route::get('/kecamatan/unpublished/{id}', ['as' => 'unpublishedKecamatanRoute', 'uses' => 'KecamatanController@unpublished']);
	/*** For Desa ***/
	Route::resource('desa', 'DesaController');
	Route::get('/get-desa', ['as' => 'getDesaRoute', 'uses' => 'DesaController@get']);
	Route::get('/desa/published/{id}', ['as' => 'publishedDesaRoute', 'uses' => 'DesaController@published']);
	Route::get('/desa/unpublished/{id}', ['as' => 'unpublishedDesaRoute', 'uses' => 'DesaController@unpublished']);
	/*** For Dapil ***/
	Route::resource('dapil', 'DapilController');
	Route::get('/get-dapil', ['as' => 'getDapilRoute', 'uses' => 'DapilController@get']);
	Route::get('/dapil/published/{id}', ['as' => 'publishedDapilRoute', 'uses' => 'DapilController@published']);
	Route::get('/dapil/unpublished/{id}', ['as' => 'unpublishedDapilRoute', 'uses' => 'DapilController@unpublished']);
	/*** For Tps ***/
	Route::resource('tps', 'TpsController');
	Route::get('/get-tps', ['as' => 'getTpsRoute', 'uses' => 'TpsController@get']);
	Route::get('/tps/published/{id}', ['as' => 'publishedTpsRoute', 'uses' => 'TpsController@published']);
	Route::get('/tps/unpublished/{id}', ['as' => 'unpublishedTpsRoute', 'uses' => 'TpsController@unpublished']);


	/*** For Caleg ***/
	Route::resource('caleg', 'CalegController');
	Route::get('/get-caleg', ['as' => 'getCalegRoute', 'uses' => 'CalegController@get']);
	Route::post('/update-caleg/{id}', ['as' => 'updateCalegRoute', 'uses' => 'CalegController@update']);
	Route::get('/caleg/published/{id}', ['as' => 'publishedCalegRoute', 'uses' => 'CalegController@published']);
	Route::get('/caleg/unpublished/{id}', ['as' => 'unpublishedCalegRoute', 'uses' => 'CalegController@unpublished']);

	/*** For Vote ***/
	Route::resource('vote', 'VoteController');
	Route::get('/get-vote', ['as' => 'getVoteRoute', 'uses' => 'VoteController@get']);
	Route::get('/vote/published/{id}', ['as' => 'publishedVoteRoute', 'uses' => 'VoteController@published']);
	Route::get('/vote/unpublished/{id}', ['as' => 'unpublishedVoteRoute', 'uses' => 'VoteController@unpublished']);

	/*** For Parpol ***/
	Route::resource('parpol', 'ParpolController');
	Route::get('/get-parpol', ['as' => 'getParpolRoute', 'uses' => 'ParpolController@get']);
	Route::get('/parpol/published/{id}', ['as' => 'publishedParpolRoute', 'uses' => 'ParpolController@published']);
	Route::get('/parpol/unpublished/{id}', ['as' => 'unpublishedParpolRoute', 'uses' => 'ParpolController@unpublished']);

	/*** For Vote ***/
	Route::resource('usergroup', 'UsergroupController');
	Route::get('/get-usergroup', ['as' => 'getUsergroupRoute', 'uses' => 'UsergroupController@get']);
	Route::get('/usergroup/published/{id}', ['as' => 'publishedUsergroupRoute', 'uses' => 'UsergroupController@published']);
	Route::get('/usergroup/unpublished/{id}', ['as' => 'unpublishedUsergroupRoute', 'uses' => 'UsergroupController@unpublished']);
	/*** For Vote ***/
	Route::resource('users', 'UserController');
	Route::get('/get-users', ['as' => 'getUserRoute', 'uses' => 'UserController@get']);
	Route::post('/update-users/{id}', ['as' => 'updateUserRoute', 'uses' => 'UserController@update_user']);
	Route::get('/users/published/{id}', ['as' => 'publishedUserRoute', 'uses' => 'UserController@published']);
	Route::get('/users/unpublished/{id}', ['as' => 'unpublishedUserRoute', 'uses' => 'UserController@unpublished']);

	/*** For Setting ***/
	Route::resource('setting', 'SettingController');
	Route::post('/setting/logo/{id}', ['as' => 'settingLogoRoute', 'uses' => 'SettingController@logo']);
	Route::post('/setting/favicon/{id}', ['as' => 'settingFaviconRoute', 'uses' => 'SettingController@favicon']);
	Route::post('/setting/general/{id}', ['as' => 'settingGeneralRoute', 'uses' => 'SettingController@general']);
	Route::post('/setting/contact/{id}', ['as' => 'settingContactRoute', 'uses' => 'SettingController@contact']);
	Route::post('/setting/address/{id}', ['as' => 'settingAddressRoute', 'uses' => 'SettingController@address']);
	Route::post('/setting/social/{id}', ['as' => 'settingSocialRoute', 'uses' => 'SettingController@social']);
	Route::post('/setting/meta/{id}', ['as' => 'settingMetaRoute', 'uses' => 'SettingController@meta']);
	Route::post('/setting/gallery-meta/{id}', ['as' => 'settingGalleryMetaRoute', 'uses' => 'SettingController@gallery_meta']);

	/*** For Profile ***/
	Route::resource('profile', 'ProfileController');
	Route::post('/profile/avatar/{id}', ['as' => 'profileAvatarRoute', 'uses' => 'ProfileController@avatar']);
	Route::post('/profile/update-password', ['as' => 'profileUpdatePasswordRoute', 'uses' => 'ProfileController@update_password']);


	/*** For Caleg Vote ***/
	Route::resource('caleg-vote', 'CalegvoteController');
	Route::get('/get-caleg-vote', ['as' => 'getCalegvoteRoute', 'uses' => 'CalegvoteController@get']);

	/*** For Vote Compare ***/
	Route::resource('vote-compare', 'VotecompareController');
	Route::get('/get-vote-compare', ['as' => 'getVotecompareRoute', 'uses' => 'VotecompareController@get']);


});

Auth::routes();

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable {
	use HasApiTokens, Notifiable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'group_id', 'tps_id', 'desa_id', 'nik', 'name', 'email', 'username', 'password', 'passmd5', 'avatar', 'role', 'activation_status', 'gender', 'phone', 'address', 'rt', 'rw', 'facebook', 'twitter', 'google_plus', 'linkedin', 'about',

	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password', 'remember_token',
	];

    public function group() {
        return $this->belongsTo(Group::class);
    }

    public function tps() {
        return $this->belongsTo(Tps::class);
    }

    public function uservotes() {
        return $this->hasMany(UserVotes::class);
    }

    public function desa() {
        return $this->belongsTo(Desa::class);
    }

}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    public function login()
    {
        if(Auth::attempt(['nik' => request('nik'), 'password' => request('password')])){
            $user = Auth::user();
            $param = array(
                'token' => $user->createToken('nApp')->accessToken, 
                'status' => true, 
            );
            return Response::json($param);
        }
        else{
            $param = array(
                'token' => 'Unuathorised', 
                'status' => false,
            ); 
            return Response::json($param);
        }
    }

    public function register()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function show(Request $request, $id=null)
    {
        if($id==null){
            $user = User::whereNotIn('activation_status', [0])->get();
        }
        else{
            $user = User::where('id', $id)->first();
        }

        return json_encode($user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')
@section('title', 'User')


@section('style')
<!-- <link rel="stylesheet" href="htuser://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
	<link rel="stylesheet" href="htuser://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css"> -->

	<link rel="stylesheet" href="{{ asset('public/admin/datatable/css/dataTables.bootstrap.min.css')}}" />
	<link rel="stylesheet" href="{{ asset('public/admin/datatable/css/buttons.dataTables.min.css')}}">
	<link rel="stylesheet" href="{{ asset('public/admin/css/jquery.inputpicker.css')}}">
	@endsection

	@section('content')
	<!-- Page header -->
	<section class="content-header">
		<h1>
			User
		</h1>
		<ol class="breadcrumb">
			<li><a href="{{ route('admin.dashboardRoute') }}"><i class="fa fa-home"></i> Dashboard</a></li>
			<li class="active">User</li>
		</ol>
	</section>
	<!-- /.page header -->

	<!-- Main content -->
	<section class="content">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Manage User</h3>

				<div class="box-tools">
					
					<a href="{{ route('admin.users.create') }}" class="btn btn-info btn-sm btn-flat"><i class="fa fa-plus"></i> Add User</a>
				</div>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<div style="width: 100%; padding-left: -10px;">
					<div class="table-responsive">
						<table id="user-table" class="table table-striped table-hover dt-responsive display nowrap" cellspacing="0">
							<thead>
								<tr>
									<th>Nama Kecamatan</th>
									<th>Nama Desa</th>
									<th>Nama User</th>
									<th>Email</th>
									<th>Group</th>
									<!-- <th>Created At</th> -->
									<!-- <th>Updated At</th> -->
									<th width="10%">Publication Status</th>
									<th width="7%">Action</th>
								</tr>
							</thead>
						</table>
					</div>
				</div>
			</div>
			<!-- /.box-body -->
			<div class="box-footer clearfix">
			</div>
		</div>
	</section>
	<!-- /.main content -->


	<!-- delete User modal -->
	<div id="delete-modal" class="modal modal-danger fade" id="modal-danger">
		<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">
						<span class="fa-stack fa-sm">
							<i class="fa fa-square-o fa-stack-2x"></i>
							<i class="fa fa-trash fa-stack-1x"></i>
						</span>
						Are you sure want to delete this ?
					</h4>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
					<form method="post" role="form" id="delete_form">
						{{csrf_field()}}
						{{method_field('DELETE')}}
						<button type="submit" class="btn btn-outline">Delete</button>
					</form>
				</div>
			</div>
			<!-- /.modal-content -->
		</div>
		<!-- /.modal-dialog -->
	</div>
	<!-- /.delete User modal -->

	<!-- view User modal -->
	<div id="user-view-modal" class="modal fade bs-example-modal-lg print-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
		<div class="modal-dialog modal-lg" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<div class="btn-group pull-right no-print">
						<div class="btn-group">
							<button class="tip btn btn-default btn-flat btn-sm" id="print-button" data-toggle="tooltip" data-original-title="Print">
								<i class="fa fa-print"></i>
								<span class="hidden-sm hidden-xs"></span>
							</button>
						</div>
						<div class="btn-group">
							<button class="tip btn btn-default btn-flat btn-sm" data-toggle="tooltip" data-original-title="Close" data-dismiss="modal" aria-label="Close">
								<i class="fa fa-remove"></i>
								<span class="hidden-sm hidden-xs"></span>
							</button>
						</div>
					</div>
					<h4 class="modal-title" id="view-name"></h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-md-9">
							<table class="table table-bordered table-striped">
								<tbody>
									<tr>
										<td width="20%">Role</td>
										<td id="view-role"></td>
									</tr>
									<tr>
										<td>Username</td>
										<td id="view-username"></td>
									</tr>
									<tr>
										<td>Email</td>
										<td id="view-email"></td>
									</tr>
									<tr>
										<td>Gender</td>
										<td id="view-gender"></td>
									</tr>
									<tr>
										<td>Phone</td>
										<td id="view-phone"></td>
									</tr>
									<tr>
										<td>Address</td>
										<td id="view-address"></td>
									</tr>
									<tr>
										<td>Facebook</td>
										<td id="view-facebook"></td>
									</tr>
									<tr>
										<td>Twitter</td>
										<td id="view-twitter"></td>
									</tr>
									<tr>
										<td>Google Plus</td>
										<td id="view-google-plus"></td>
									</tr>
									<tr>
										<td>Linkedin</td>
										<td id="view-linkedin"></td>
									</tr>
									<tr>
										<td>Status</td>
										<td id="view-status"></td>
									</tr>
									<tr>
										<td>About</td>
										<td id="view-about"></td>
									</tr>
								</tbody>
							</table>
						</div>
						<div class="col-md-3">
							<img id="view-avatar" class="img-responsive img-thumbnail img-rounded">
						</div>
					</div>
				</div>
				<div class="modal-footer no-print">
					<button type="button" class="btn btn-default btn-flat" data-dismiss="modal" aria-label="Close">Close</button>
				</div>
			</div>
		</div>
	</div>
	<!-- /.view User modal -->
	@endsection

	@section('script')
	<script type="text/javascript" src="{{ asset('public/admin/datatable/js/jquery.dataTables.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/admin/datatable/js/datatables.bootstrap.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/admin/datatable/js/dataTables.buttons.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/admin/datatable/js/buttons.flash.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/admin/datatable/js/pdfmake.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/admin/datatable/js/vfs_fonts.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/admin/datatable/js/buttons.html5.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/admin/datatable/js/buttons.print.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/admin/datatable/js/buttons.colVis.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/admin/js/jquery.inputpicker.js') }}"></script>

	<script type="text/javascript">
		/** Load datatable **/
		$(document).ready(function() {
			get_table_data();

			var disabled_form = "{{isAdmin()}}";

			if(disabled_form){
				var url = "{{ route('allKabupatenRoute') }}";
				$.ajax({
					url: url,
					method: "GET",
					dataType: "json",
					success:function(result){

						var kabupaten = '<label><select id="kabupaten_id" name="kabupaten_id" aria-controls="user-table" class="form-control" style="width:150px; margin-left:5px;">';
					  	
					  	kabupaten += '<option value="" selected disabled>pilih kabupaten</option>';

						result.data.forEach(function(item){
						  kabupaten += '<option value="'+item.id+'">'+item.kabupaten_name+'</option>';
						});

					  	kabupaten += '</select></label>';
						
						$("#user-table_length").append(kabupaten);

					}

				});

			}

		});

		/** Delete **/
		$("#user-table").on("click", ".delete-button", function(){
			var user_id = $(this).data("id");
			var url = "{{ route('admin.users.destroy', 'user_id') }}";
			url = url.replace("user_id", user_id);
			$('#delete-modal').modal('show');
			$('#delete_form').attr('action', url);
		});

		/** View **/
		$("#user-table").on("click", ".view-button", function(){
			var user_id = $(this).data("id");
			var url = "{{ route('admin.users.show', 'user_id') }}";
			url = url.replace("user_id", user_id);
			$.ajax({
				url: url,
				method: "GET",
				dataType: "json",
				success:function(data){
					$('#view-modal').modal('show');
					$('#view-user-name-title').text(data.user.name);
					$('#view-user-name').text(data.user.name);
					if(data.user.activation_status == 1){
						$('#view-publication-status').text('Published');
					}else{
						$('#view-publication-status').text('Unpublished');
					}
				}});
		});


		$(".table-responsive").on('change', '#kabupaten_id', function(){
	        $('#user-table').DataTable().ajax.reload();

		});

		/** Get datatable **/
		function get_table_data(){

			$('#user-table').DataTable({
				dom: 'Blfrtip',
				buttons: [
				{ extend: 'copy', exportOptions: { columns: ':visible'}},
				{ extend: 'print', exportOptions: { columns: ':visible'}},
				{ extend: 'pdf', orientation: 'landscape', pageSize: 'A4', exportOptions: { columns: ':visible'}},
				{ extend: 'csv', exportOptions: { columns: ':visible'}},
				{ extend: 'colvis', text:'Column'},
				],
				columnDefs: [ {
					targets: -1,
					visible: true
				} ],
				lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
				processing: true,
				serverSide: true,
				ajax: {
					"type"   : "GET",
					"url"    : "{{ route('admin.getUserRoute') }}",
					"data"   : function( d ) {
							      d.kabupaten_id 	= $('#kabupaten_id').val();
							   },
    				// "dataSrc": ""
				},
				columns: [
				{data: 'kecamatan_name', name: 'kecamatan.kecamatan_name'},
				{data: 'desa_name', name: 'desa.desa_name'},
				{data: 'name', name: 'users.name'},
				{data: 'email', name: 'users.email'},
				{data: 'group_name', name: 'groups.group_name'},
				// {data: 'created_at', name: 'users.created_at'},
				// {data: 'updated_at', name: 'users.updated_at'},
				{data: function (data, type, row) {
							if(data.activation_status == 1){
								var url_unpublish = "{{ route('admin.unpublishedUserRoute', 'user_id') }}";
								url_unpublish = url_unpublish.replace("user_id", data.id);

								var publication = '<a href="'+url_unpublish+'" class="btn btn-success btn-xs btn-flat btn-block" data-toggle="tooltip" data-original-title="Click to Unactivate"><i class="icon fa fa-arrow-down"></i>Activate</a>';
							}
							else{
								var url_publish = "{{ route('admin.publishedUserRoute', 'user_id') }}";
								url_publish = url_publish.replace("user_id", data.id);

								var publication = '<a href="'+url_publish+'" class="btn btn-warning btn-xs btn-flat btn-block" data-toggle="tooltip" data-original-title="Click to Activate"><i class="icon fa fa-arrow-up"></i> Unactivate</a>'

							}
		                    return publication;
                },orderable: false, searchable: false},
                // 'publication_status', name: 'publication_status', orderable: false, searchable: false},
				{data: function (data, type, row) {
							var url_edit = "{{ route('admin.users.edit', 'user_id') }}";
							url_edit = url_edit.replace("user_id", data.id);

							var action = '<button style="margin-right:3px;" class="btn btn-info btn-xs user-view-button" data-id="' + data.id + '" data-toggle="tooltip" data-original-title="View"><i class="fa fa-eye"></i></button>'+ 
                				'<a style="margin-right:3px;" class="btn btn-primary btn-xs edit-button" href="'+url_edit+'" data-toggle="tooltip" data-original-title="Edit"><i class="fa fa-edit"></i></a>'+
                    			'<button style="margin-right:3px;" class="btn btn-danger btn-xs delete-button" data-id="' + data.id + '"data-toggle="tooltip" data-original-title="Delete"><i class="fa fa-trash"></i></button>';
		                    return action;
                }, orderable: false, searchable: false},
				],
				order: [[3, 'desc']],
			});
		}

		/** User View **/
		$("#user-table").on("click", ".user-view-button", function(){
			var id = $(this).data("id");
			var url = "{{ route('admin.users.show', 'id') }}";
			url = url.replace("id", id);
			$.ajax({
				url: url,
				method: "GET",
				dataType: "json",
				success:function(data){
					var src = '{{ asset('public/avatar') }}/';
					var default_avatar = '{{ asset('public/avatar/user.png') }}';
					$('#user-view-modal').modal('show');

					$('#view-name').text(data['name']);
					$('#view-username').text(data['username']);
					$('#view-email').text(data['email']);
					$("#view-avatar").attr("src", src+data['avatar']);
					if(data['avatar']){
						$("#view-avatar").attr("src", src+data['avatar']);
					}else{
						$("#view-avatar").attr("src", default_avatar);
					}
					if(data['gender'] == 'm'){
						$('#view-gender').text('Male');
					}else{
						$('#view-gender').text('Female');
					}
					$('#view-phone').text(data['phone']);
					$('#view-address').text(data['address']);
					$('#view-facebook').text(data['facebook']);
					$('#view-twitter').text(data['twitter']);
					$('#view-google-plus').text(data['google_plus']);
					$('#view-linkedin').text(data['linkedin']);
					$('#view-about').text(data['about']);
					if(data['role'] == 'admin'){
						$('#view-role').text('Admin');
					}else{
						$('#view-role').text('User');
					}
					if(data['activation_status'] == 1){
						$('#view-status').text('Active');
					}else{
						$('#view-status').text('Block');
					}
				}});
		});
	</script>
	@endsection