routes/web.php
<?php

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    // Ignores notices and reports all other kinds... and warnings
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
    // error_reporting(E_ALL ^ E_WARNING); // Maybe this is enough
}

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => '/'], function () {
	Route::get('/', ['as' => 'homePage', 'uses' => 'WebController@index']);
	Route::get('/filter-caleg', ['as' => 'filterCaleg', 'uses' => 'WebController@get']);
	Route::get('/mobile', ['as' => 'mobilePage', 'uses' => 'WebController@mobile']);
	Route::get('/get-all-vote', ['as' => 'allVoteRoute', 'uses' => 'VoteController@show']);
	Route::get('/get-all-parpol', ['as' => 'allParpolRoute', 'uses' => 'ParpolController@show']);
	Route::get('/get-all-kabupaten', ['as' => 'allKabupatenRoute', 'uses' => 'KabupatenController@show']);
	Route::get('/get-all-kecamatan', ['as' => 'allKecamatanRoute', 'uses' => 'KecamatanController@show']);
	Route::get('/get-all-desa', ['as' => 'allDesaRoute', 'uses' => 'DesaController@show']);
	Route::get('/get-all-dapil', ['as' => 'allDapilRoute', 'uses' => 'DapilController@show']);
	Route::get('/get-all-wilayahdapil/{id}', ['as' => 'allWilayahdapilRoute', 'uses' => 'DapilController@area']);
	Route::get('/get-all-wilayahdetail/{id}', ['as' => 'wilayahDetailRoute', 'uses' => 'DapilController@area_detail']);
	Route::get('/get-all-tps', ['as' => 'allTpsRoute', 'uses' => 'TpsController@show']);
	Route::get('/get-all-usergroup', ['as' => 'allUsergroupRoute', 'uses' => 'UsergroupController@show']);
	Route::get('/get-all-caleggroup', ['as' => 'allCaleggroupRoute', 'uses' => 'CaleggroupController@show']);
	Route::get('/get-all-caleg', ['as' => 'allCalegRoute', 'uses' => 'CalegController@show']);
	
});

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin'], 'as' => 'admin.'], function () {
	Route::get('/dashboard', ['as' => 'dashboardRoute', 'uses' => 'DashboardController@index']);


	/*** For Master ***/
	/*** For Kabupaten ***/
	Route::resource('kabupaten', 'KabupatenController');
	Route::get('/get-kabupaten', ['as' => 'getKabupatenRoute', 'uses' => 'KabupatenController@get']);
	Route::get('/kabupaten/published/{id}', ['as' => 'publishedKabupatenRoute', 'uses' => 'KabupatenController@published']);
	Route::get('/kabupaten/unpublished/{id}', ['as' => 'unpublishedKabupatenRoute', 'uses' => 'KabupatenController@unpublished']);
	/*** For Kecamatan ***/
	Route::resource('kecamatan', 'KecamatanController');
	Route::get('/get-kecamatan', ['as' => 'getKecamatanRoute', 'uses' => 'KecamatanController@get']);
	Route::get('/kecamatan/published/{id}', ['as' => 'publishedKecamatanRoute', 'uses' => 'KecamatanController@published']);
	Route::get('/kecamatan/unpublished/{id}', ['as' => 'unpublishedKecamatanRoute', 'uses' => 'KecamatanController@unpublished']);
	/*** For Desa ***/
	Route::resource('desa', 'DesaController');
	Route::get('/get-desa', ['as' => 'getDesaRoute', 'uses' => 'DesaController@get']);
	Route::get('/desa/published/{id}', ['as' => 'publishedDesaRoute', 'uses' => 'DesaController@published']);
	Route::get('/desa/unpublished/{id}', ['as' => 'unpublishedDesaRoute', 'uses' => 'DesaController@unpublished']);
	/*** For Dapil ***/
	Route::resource('dapil', 'DapilController');
	Route::get('/get-dapil', ['as' => 'getDapilRoute', 'uses' => 'DapilController@get']);
	Route::get('/dapil/published/{id}', ['as' => 'publishedDapilRoute', 'uses' => 'DapilController@published']);
	Route::get('/dapil/unpublished/{id}', ['as' => 'unpublishedDapilRoute', 'uses' => 'DapilController@unpublished']);
	/*** For Tps ***/
	Route::resource('tps', 'TpsController');
	Route::get('/get-tps', ['as' => 'getTpsRoute', 'uses' => 'TpsController@get']);
	Route::get('/tps/published/{id}', ['as' => 'publishedTpsRoute', 'uses' => 'TpsController@published']);
	Route::get('/tps/unpublished/{id}', ['as' => 'unpublishedTpsRoute', 'uses' => 'TpsController@unpublished']);


	/*** For Caleg ***/
	Route::resource('caleg', 'CalegController');
	Route::get('/get-caleg', ['as' => 'getCalegRoute', 'uses' => 'CalegController@get']);
	Route::post('/update-caleg/{id}', ['as' => 'updateCalegRoute', 'uses' => 'CalegController@update']);
	Route::get('/caleg/published/{id}', ['as' => 'publishedCalegRoute', 'uses' => 'CalegController@published']);
	Route::get('/caleg/unpublished/{id}', ['as' => 'unpublishedCalegRoute', 'uses' => 'CalegController@unpublished']);

	/*** For Vote ***/
	Route::resource('vote', 'VoteController');
	Route::get('/get-vote', ['as' => 'getVoteRoute', 'uses' => 'VoteController@get']);
	Route::get('/vote/published/{id}', ['as' => 'publishedVoteRoute', 'uses' => 'VoteController@published']);
	Route::get('/vote/unpublished/{id}', ['as' => 'unpublishedVoteRoute', 'uses' => 'VoteController@unpublished']);

	/*** For Parpol ***/
	Route::resource('parpol', 'ParpolController');
	Route::get('/get-parpol', ['as' => 'getParpolRoute', 'uses' => 'ParpolController@get']);
	Route::get('/parpol/published/{id}', ['as' => 'publishedParpolRoute', 'uses' => 'ParpolController@published']);
	Route::get('/parpol/unpublished/{id}', ['as' => 'unpublishedParpolRoute', 'uses' => 'ParpolController@unpublished']);

	/*** For Vote ***/
	Route::resource('usergroup', 'UsergroupController');
	Route::get('/get-usergroup', ['as' => 'getUsergroupRoute', 'uses' => 'UsergroupController@get']);
	Route::get('/usergroup/published/{id}', ['as' => 'publishedUsergroupRoute', 'uses' => 'UsergroupController@published']);
	Route::get('/usergroup/unpublished/{id}', ['as' => 'unpublishedUsergroupRoute', 'uses' => 'UsergroupController@unpublished']);
	/*** For Vote ***/
	Route::resource('users', 'UserController');
	Route::get('/get-users', ['as' => 'getUserRoute', 'uses' => 'UserController@get']);
	Route::post('/update-users/{id}', ['as' => 'updateUserRoute', 'uses' => 'UserController@update_user']);
	Route::get('/users/published/{id}', ['as' => 'publishedUserRoute', 'uses' => 'UserController@published']);
	Route::get('/users/unpublished/{id}', ['as' => 'unpublishedUserRoute', 'uses' => 'UserController@unpublished']);

	/*** For Setting ***/
	Route::resource('setting', 'SettingController');
	Route::post('/setting/logo/{id}', ['as' => 'settingLogoRoute', 'uses' => 'SettingController@logo']);
	Route::post('/setting/favicon/{id}', ['as' => 'settingFaviconRoute', 'uses' => 'SettingController@favicon']);
	Route::post('/setting/general/{id}', ['as' => 'settingGeneralRoute', 'uses' => 'SettingController@general']);
	Route::post('/setting/contact/{id}', ['as' => 'settingContactRoute', 'uses' => 'SettingController@contact']);
	Route::post('/setting/address/{id}', ['as' => 'settingAddressRoute', 'uses' => 'SettingController@address']);
	Route::post('/setting/social/{id}', ['as' => 'settingSocialRoute', 'uses' => 'SettingController@social']);
	Route::post('/setting/meta/{id}', ['as' => 'settingMetaRoute', 'uses' => 'SettingController@meta']);
	Route::post('/setting/gallery-meta/{id}', ['as' => 'settingGalleryMetaRoute', 'uses' => 'SettingController@gallery_meta']);

	/*** For Profile ***/
	Route::resource('profile', 'ProfileController');
	Route::post('/profile/avatar/{id}', ['as' => 'profileAvatarRoute', 'uses' => 'ProfileController@avatar']);
	Route::post('/profile/update-password', ['as' => 'profileUpdatePasswordRoute', 'uses' => 'ProfileController@update_password']);


	/*** For Caleg Vote ***/
	Route::resource('caleg-vote', 'CalegvoteController');
	Route::get('/get-caleg-vote', ['as' => 'getCalegvoteRoute', 'uses' => 'CalegvoteController@get']);

	/*** For Vote Compare ***/
	Route::resource('vote-compare', 'VotecompareController');
	Route::get('/get-vote-compare', ['as' => 'getVotecompareRoute', 'uses' => 'VotecompareController@get']);


});

Auth::routes();

resources/views/admin/includes/flash_notification.blade.php
  <div class='col-xs-6 col-sm-6 col-md-3 alert bootstrap-growl-bottom-right alert-success' id='message_box' style='position: fixed; margin: 0px; z-index: 1080; bottom: -60px; right: 20px;'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button><i class='icon fa fa-check'></i>{{ !empty(Session::get('message')) ? Session::get('message') : '' }}</div>

  <div class='col-xs-6 col-sm-6 col-md-3 alert bootstrap-growl-bottom-right alert-warning' id='exception_box' style='position: fixed; margin: 0px; z-index: 1080; bottom: -60px; right: 20px;'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button><i class='icon fa fa-warning'></i>{{ !empty(Session::get('exception')) ? Session::get('exception') : '' }}</div>

resources/views/admin/includes/footer.blade.php
  <footer class="main-footer">
  	<!-- <div class="pull-right hidden-xs">
  		<b>Version</b> 2.4.0
  	</div> -->
  	{!! $setting->copyright !!}
  </footer>

resources/views/admin/includes/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>@yield('title')</title>
<!-- Tell the browser to be responsive to screen width -->
<link rel="shortcut icon"  href="{{ asset('public/web/favicon/favicon.png') }}" />
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{ asset('public/admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('public/admin/bower_components/font-awesome/css/font-awesome.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{ asset('public/admin/bower_components/Ionicons/css/ionicons.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('public/admin/dist/css/AdminLTE.min.css') }}">
<!-- Parsley form validation -->
<link rel="stylesheet" href="{{ asset('public/admin/css/parsley.css') }}">
<!-- Custom Style -->
<link rel="stylesheet" href="{{ asset('public/admin/css/style.css') }}">
<!-- Summernote editor -->
<link href="{{ asset('public/admin/summernote/summernote.css') }}" rel="stylesheet">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
   folder instead of downloading all of them to reduce the load. -->
   <link rel="stylesheet" href="{{ asset('public/admin/dist/css/skins/_all-skins.min.css') }}">

   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
   <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" href="{{ asset('public/common/css/notif.alert.css') }}">

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/admin/includes/header.blade.php
<!-- Logo -->
<a href="{{ route('admin.dashboardRoute') }}" class="logo">
  <!-- mini logo for sidebar mini 50x50 pixels -->
  <span class="logo-mini"><b>GKR</b></span>
  <!-- logo for regular state and mobile devices -->
  <span class="logo-lg"><b>CARINGIN SAJATI</b></span>
</a>
<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </a>

  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <!-- frontend -->
      <li class="user user-menu">
        <a href="{{ route('homePage') }}" target="_blank">
          <img src="{{ asset('public/admin/image/frontend.png') }}" class="user-image img-responsive" alt="Frontend" width="25px">
          <span class="hidden-xs">Frontend</span>
        </a>
      </li>
      <!-- /.frontend -->

      <!-- user -->
      <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          @if(!empty(Auth::user()->avatar))
          <img src="{{ asset('public/avatar/' . Auth::user()->avatar) }}" class="user-image" alt="{{ Auth::user()->name }}">
          @else
          <img src="{{ asset('public/avatar/user.png') }}" class="user-image" alt="{{ Auth::user()->name }}">
          @endif
          <span class="hidden-xs">{{ Auth::user()->name }}</span>
        </a>
        <ul class="dropdown-menu">
          <!-- User image -->
          <li class="user-header">
            @if(!empty(Auth::user()->avatar))
            <img src="{{ asset('public/avatar/'. Auth::user()->avatar) }}" class="img-circle" alt="{{ Auth::user()->name }}">
            @else
            <img src="{{ asset('public/avatar/user.png') }}" class="img-circle" alt="{{ Auth::user()->name }}">
            @endif
            <p>
              {{ Auth::user()->name }} - {{ Auth::user()->role }}
              <small>Member Since {{ date("d F Y", strtotime(Auth::user()->created_at)) }} </small>
            </p>
          </li>
          <!-- Menu Footer-->
          <li class="user-footer">
            <div class="pull-left">
              <a href="{{ route('admin.profile.index') }}" class="btn btn-default btn-flat">Profile</a>
            </div>
            <div class="pull-right">
              <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form1').submit();">Sign out</a>
              <form id="logout-form1" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
              </form>
            </div>
          </li>
        </ul>
      </li>
      <!-- /.user -->

      <!-- setting -->
      <li class="user user-menu"><a href="{{ route('admin.setting.index') }}"><span class="hidden-xs"><i class="fa fa-gears"></i></span></a></li>
      <!-- /.setting -->

    </ul>
  </div>
</nav>

resources/views/admin/includes/scripts.blade.php
<!-- jQuery 3 -->
<script src="{{ asset('public/admin/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('public/admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('public/admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('public/admin/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('public/admin/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('public/admin/dist/js/demo.js') }}"></script>
<!-- Parsley form validation -->
<script src="{{ asset('public/admin/js/parsley.min.js') }}"></script>
<!-- Summernote editor -->
<script src="{{ asset('public/admin/summernote/summernote.js') }}"></script>

<script src="{{ asset('public/common/js/notif.alert.js') }}"></script>

<script>
  $(document).ready(function () {
    $('.sidebar-menu').tree();
  })
</script>

<!-- Notification Message -->
@if (!empty(Session::get('message')))
<script>
  $(document).ready(function () {
    $('.alert-success').animate({ top: "0" }, 500).show();
    setTimeout(function(){
        hideAllMessages();
    }, 4000);
  })
</script>
@endif

<!-- Notification Exception -->
@if (!empty(Session::get('exception')))
<script>
  $(document).ready(function () {
    $('.alert-danger').animate({ top: "0" }, 500).show();
    setTimeout(function(){
        hideAllMessages();
    }, 4000);
  })
</script>
@endif

<!-- Activate Menu -->
<script type="text/javascript">
 $('#mainMenu ul li').find('a').each(function () {
  if (document.location.href == $(this).attr('href')) {
    $(this).parents().addClass("active");
    $(this).addClass("active");
  }
});
</script>

<!-- For Modal Print -->
<script type="text/javascript">
  $('#print-button').on('click', function () {
    if ($('.print-modal').is(':visible')) {
      var modalId = $(event.target).closest('.print-modal').attr('id');
      $('body').css('visibility', 'hidden');
      $("#" + modalId).css('visibility', 'visible');
      $('#' + modalId).removeClass('print-modal');
      window.print();
      $('body').css('visibility', 'visible');
      $('#' + modalId).addClass('print-modal');
    } else {
      window.print();
    }
  });
</script>

<!-- For Div Print -->
<script type="text/javascript">
  function printDiv(printable_area) {
   var printContents = document.getElementById(printable_area).innerHTML;
   var originalContents = document.body.innerHTML;
   document.body.innerHTML = printContents;
   window.print();
   document.body.innerHTML = originalContents;
 }
</script>

<!-- For Tooltip -->
<script type="text/javascript">
  $('body').tooltip({selector: '[data-toggle="tooltip"]'});
</script>

resources/views/admin/includes/sidebar.blade.php
   <!-- sidebar: style can be found in sidebar.less -->
   <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        @if(!empty(Auth::user()->avatar))
        <img src="{{ asset('public/avatar/' . Auth::user()->avatar) }}" class="img-circle" alt="{{ Auth::user()->name }}">
        @else
        <img src="{{ asset('public/avatar/user.png') }}" class="img-circle" alt="{{ Auth::user()->name }}">
        @endif
      </div>
      <div class="pull-left info">
        <p>{{ Auth::user()->name }}</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <div id="mainMenu">
      <ul class="sidebar-menu" data-widget="tree">
        <!-- <li class="{{ Request::is('admin/dashboard') ? "active" : '' }}"><a href="{{ route('admin.dashboardRoute') }}"><i class="fa fa-home"></i> <span>Dashboard</span></a></li> -->
        <li><a href="{{ route('admin.dashboardRoute') }}"><i class="fa fa-home text-yellow"></i> <span>Dashboard</span></a></li>
        @if(isAdmin())
        <li class="treeview">
          <a href="#">
            <i class="fa fa-file text-yellow"></i> <span>Master</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ route('admin.dapil.index') }}"><i class="fa fa-circle-o"></i> Dapil</a></li>
            <li><a href="{{ route('admin.kabupaten.index') }}"><i class="fa fa-circle-o"></i> Kabupaten</a></li>
            <li><a href="{{ route('admin.kecamatan.index') }}"><i class="fa fa-circle-o"></i> Kecamatan</a></li>
            <li><a href="{{ route('admin.desa.index') }}"><i class="fa fa-circle-o"></i> Desa</a></li>
            <li><a href="{{ route('admin.tps.index') }}"><i class="fa fa-circle-o"></i> TPS</a></li>
          </ul>
        </li>

        <li><a href="{{ route('admin.caleg.index') }}"><i class="fa fa-users text-yellow"></i> <span>Caleg</span></a></li>
        @endif

        <li class="treeview">
          <a href="#">
            <i class="fa fa-list text-yellow"></i> <span>Laporan</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ route('admin.vote.index') }}"><i class="fa fa-circle-o"></i> Rekap Caleg</a></li>
            <li><a href="{{ route('admin.parpol.index') }}"><i class="fa fa-circle-o"></i> Rekap Partai</a></li>
            <li><a href="{{ route('admin.vote-compare.index') }}"><i class="fa fa-circle-o"></i> Prosentase Suara</a></li>
            <li><a href="{{ route('admin.caleg-vote.index') }}"><i class="fa fa-circle-o"></i> Perolehan Percaleg</a></li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-user text-yellow"></i> <span>User</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            @if(isAdmin())
            <li><a href="{{ route('admin.usergroup.index') }}"><i class="fa fa-circle-o"></i> User Group</a></li>
            @endif
            <li><a href="{{ route('admin.users.index') }}"><i class="fa fa-circle-o"></i> User List</a></li>
          </ul>
        </li>
        <li><a href="{{ route('admin.setting.index') }}"><i class="fa fa-gears text-yellow"></i> <span>Setting</span></a></li>
        <li class="header">LABELS</li>
        <li><a href="{{ route('admin.profile.index') }}"><i class="fa fa-user text-yellow"></i> <span>Profile</span></a></li>
        <li>
          <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-lock text-yellow"></i>Sign out</a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
          </form>
        </li>
      </ul>
    </div>
  </section>
    <!-- /.sidebar -->